<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
	<WebRoot>wwwroot</WebRoot>
    <EnableDefaultContentItems>false</EnableDefaultContentItems>
  </PropertyGroup>

	<PropertyGroup>
		<MSBuildWarningsAsErrors></MSBuildWarningsAsErrors>
		<NoWarn>NU1903</NoWarn>
	</PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.0-*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.0-*">
		<PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fayora.Application\Fayora.Application.csproj" />
    <ProjectReference Include="..\Fayora.Contracts\Fayora.Contracts.csproj" />
    <ProjectReference Include="..\Fayora.Infrastructure\Fayora.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\fayora-app-firebase-adminsdk-fbsvc-b841a1bd04.json" Link="fayora-app-firebase-adminsdk-fbsvc-b841a1bd04.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
